CREATE DATABASE IF NOT EXISTS bd_dev;

use bd_dev;

CREATE TABLE IF NOT EXISTS users (
    user_id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(155) NOT NULL, 
    PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS projects (
    project_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(155) NOT NULL,
    PRIMARY KEY(project_id)
);
